#!/bin/bash

# Force Fresh Login Script
# This script helps you test with a completely clean state

echo "=================================================="
echo "🔄 FORCE FRESH LOGIN"
echo "=================================================="
echo ""
echo "This will help you start with a clean state."
echo ""
echo "📋 STEPS TO FOLLOW:"
echo ""
echo "1. Open Browser DevTools (F12)"
echo "2. Go to Application → Storage → Clear site data"
echo "3. Close all localhost:3000 tabs"
echo "4. Open NEW incognito/private window"
echo "5. Go to: http://localhost:3000"
echo "6. You'll be redirected to login"
echo "7. Login with: karthikelangovan04 / your_password"
echo ""
echo "8. Check Browser Console for these logs:"
echo "   🔐 LOGIN: Set user cookie - copilot_adk_user_id=3"
echo "   🍪 SET USER COOKIE: copilot_adk_user_id=3"
echo "   🍪 SET SESSION COOKIE: copilot_adk_session_id=..."
echo ""
echo "9. Check DevTools → Application → Cookies:"
echo "   ✅ copilot_adk_user_id = 3"
echo "   ✅ copilot_adk_session_id = <uuid>"
echo ""
echo "10. Send a message in the chat"
echo ""
echo "11. Run verification:"
echo "    ./verify-chat-data.sh"
echo ""
echo "    Should show: ✅ Numeric User ID (user_id = 3)"
echo ""
echo "=================================================="
echo ""
read -p "Press Enter when you've completed the steps above..."
echo ""
echo "Running database verification..."
echo ""
./verify-chat-data.sh
